-- ===================================================
-- THE CHORUS - SUPABASE ANNOUNCEMENTS TABLE SETUP
-- Run this SQL in your Supabase Dashboard -> SQL Editor
-- ===================================================

-- 1. Create the announcements table
CREATE TABLE IF NOT EXISTS public.announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week TEXT NOT NULL,
    month TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;

-- 3. Create Policies for Public Access (anon & authenticated)
-- Allow anyone to view announcements
CREATE POLICY "Allow public read announcements" 
ON public.announcements 
FOR SELECT 
TO anon, authenticated 
USING (true);

-- Allow anyone to add an announcement
CREATE POLICY "Allow public insert announcements" 
ON public.announcements 
FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

-- Allow anyone to delete an announcement
CREATE POLICY "Allow public delete announcements" 
ON public.announcements 
FOR DELETE 
TO anon, authenticated 
USING (true);

-- 4. Enable Realtime sync across all devices
ALTER PUBLICATION supabase_realtime ADD TABLE public.announcements;

-- 5. Insert initial default announcements
INSERT INTO public.announcements (week, month, message) VALUES
('Week 1', 'March 2025', '🎵 New song rehearsal scheduled for Friday at 6 PM. All band members please be present.'),
('Week 2', 'March 2025', '🥁 Sound check for upcoming concert. Equipment setup at 4 PM.'),
('Week 3', 'March 2025', '🎸 New album recording session. Studio booked for whole day Saturday.'),
('Week 4', 'March 2025', '🎤 Final rehearsal before the big show! Don''t miss it.');
